### ISSUE TITLE
Extra if statement

### ISSUE THREAD

**Issue by sen1** [yuunaK/intro-data-capstone-biodiversity#5]
https://github.com/yuunaK/intro-data-capstone-biodiversity/blob/271477e13af1bf097085ee5824626b8eb9231fba/Yuuna_Mathew_Biodiversity_Capstone/biodiversity3.py#L530

'Sheep' in commonName already returns a boolean. No need of the if statement in there. Check the simplified version below.
species['is_sheep'] = species.common_names.apply(lambda commonName: 'Sheep' in commonName)

**Comment by yuunaK** [comment]
Thank you for this clarification.  I understand this simplified version.  I opted not to use it for my code at this time because I wanted to make explicit the logic to myself when I read it later.  Again, I was thinking of being able to read my code later and understand what I was doing.  Maybe I will find all these things I am doing unnecessary because I will already understand what it means.  I am thinking ahead to perhaps forgetting and needing some clue as to what I am doing without having to write a comment.

With regard to creating arrays,
There are two things you can do when creating a new column for a dataframe using an existing column in the dataframe
you can create a boolean column - you can create a column of true / false.
you can create a modified column which operates on either the values that are true or false to create a final column which is not strictly boolean but its values depend on a prior boolean operation.
