### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by sen1** [yuunaK/intro-data-capstone-biodiversity#6]
Great work! I probably won’t have much to say here because you pretty much nailed it all the way through.

Your Python work is excellent and very readable. As I mentioned use nunique() than count() to count unique number of species. You dont want to double count them. When making a plot make sure you have the right order of first plotting, then labeling, titling etc.

Presentation: I think your graphs look excellent. Also, your conclusions were succinct and on point, so great work there. I loved the explanation about the calculations you made to reach them (with p-values, etc). 

Excellent work overall.

**Comment by yuunaK** [comment]
Thank you Abhisek.  With regard to count() and nunique(), I included both to show how the two functions produce different results.  Maybe readers of the code might not find that valuable.  But I was intrigued by how using different methods can throw your results and I wanted the information present side by side so that in future I will be reminded of this lesson.  Once again, thank you very much for taking time to review my work and provide your valuable feedback.
